### ISSUE TITLE
非常感谢贵团队共享的代码。有一个疑问想请教贵团队

### ISSUE THREAD

**Issue by studyrec** [HKUDS/SSLRec#23]
我在configurator文件中指定了3号显卡，但是报错却是0号显卡内存不足，请问这种情况我还怎么处理，感谢。

**configurator.py文件**
```
def parse_configure():
    parser = argparse.ArgumentParser(description='SSLRec')
    parser.add_argument('--model', type=str, default='SGL', help='model name')
    parser.add_argument('--dataset', type=str, default='iFashion', help='dataset name (yelp, gowalla, '
                                                                        'iFashion, beauty)')
    parser.add_argument('--device', type=str, default='cuda', help='cpu or cuda')
    parser.add_argument('--cuda', type=str, default='3', help='Device number')
    args = parser.parse_args()

    if args.device == 'cuda':
        os.environ['CUDA_VISIBLE_DEVICES'] = args.cuda

        print('Used GPU ID:',args.cuda)
```

**输出信息如下**

Used GPU ID: 3
SGL(
  (edge_dropper): EdgeDrop()
  (node_dropper): NodeDrop()
)
{'optimizer': {'name': 'adam', 'lr': 0.001, 'weight_decay': 0}, 'train': {'epoch': 300, 'batch_size': 4096, 'save_model': False, 'loss': 'pairwise', 'log_loss': False, 'test_step': 1, 'patience': 20, 'reproducible': True, 'seed': 2023, 'early_stop': True}, 'test': {'metrics': ['recall', 'ndcg'], 'k': [10, 20], 'batch_size': 2048}, 'data': {'type': 'general_cf', 'name': 'iFashion', 'user_num': 300000, 'item_num': 81613}, 'model': {'name': 'sgl', 'keep_rate': 0.5, 'layer_num': 2, 'reg_weight': 1e-05, 'cl_weight': 1.0, 'temperature': 0.2, 'embedding_size': 64, 'augmentation': 'edge_drop'}, 'tune': {'enable': False, 'hyperparameters': ['layer_num', 'reg_weight', 'cl_weight', 'temperature'], 'layer_num': [2, 3, 4], 'reg_weight': [0.0001, 1e-05, 1e-06, 1e-07, 1e-08], 'cl_weight': [0.01, 0.05, 0.1, 0.5, 1.0], 'temperature': [0.1, 0.2, 0.5, 1.0]}, 'device': 'cuda'}
Training Recommender:   0%|          | 1/315 [00:05<27:43,  5.30s/it]

**torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.58 GiB** (**GPU 0**; 23.69 GiB total capacity; 5.42 GiB already allocated; 3.26 GiB free; 10.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Process finished with exit code 1

**我的显卡情况如下**
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.version.cuda)
print(torch.cuda.current_device())
print(torch.cuda.get_device_name())

输出信息
True
4
11.7
0
NVIDIA GeForce RTX 3090

**Comment by Re-bin** [comment]
嗨 👋

感谢关注！当使用`os.environ['CUDA_VISIBLE_DEVICES'] = ‘3’`指定显卡过后，相对于当前运行的PyThon进程而言，该显卡（服务器中编号为3的显卡）就是（该进程的）第0个显卡，所以会显示0。

可以使用`nivida-smi`或者`gpustat -i`查看一下当前的显存占用情况 :)

Best regards,
Xubin

**Comment by studyrec** [comment]
> 嗨 👋
> 
> 感谢关注！当使用`os.environ['CUDA_VISIBLE_DEVICES'] = ‘3’`指定显卡过后，相对于当前运行的PyThon进程而言，该显卡（服务器中编号为3的显卡）就是（该进程的）第0个显卡，所以会显示0。
> 
> 可以使用`nivida-smi`或者`gpustat -i`查看一下当前的显存占用情况 :)
> 
> Best regards, Xubin

好的，已解决，非常感谢您的回复！祝好。
